### Test the Simple Book API with REST Client (extention for VSCode)
// This file contains a collection of HTTP requests to test the Simple Book API.
// Make sure to start the server before running these requests.
// You can run the server using the command: node server.js

### Welcome message
GET http://localhost:3000/


###
# Get a book by ID
GET http://localhost:3000/api/books/682958ed5cf34cc6cb34a470

###
# Get all books
GET http://localhost:3000/api/books/

###
# Add a new book
POST http://localhost:3000/api/books
Content-Type: application/json

{
  "title": "New Book Title",
  "author": "Author Name",
}

###
# Update a book by ID
PATCH http://localhost:3000/api/books/682958ed5cf34cc6cb34a470
Content-Type: application/json

{
  "author": "Patched Title"
}

###
# Delete a book by ID
DELETE http://localhost:3000/api/books/68278d9a6466607468295f5ce48c493996916b5e1f4f535d